name: thepointapp
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1
#sdk: '>=3.3.4 <4.0.0'
environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_database: ^11.0.3
  firebase_messaging: ^15.0.3
  firebase_storage: ^12.1.1
  flutter:
    sdk: flutter
  flutter_polyline_points: ^2.1.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.7.0
  http: ^1.2.1
  json_annotation: ^4.9.0
  location: ^7.0.0
  lottie: ^3.0.0
  overlay_support: ^2.1.0
  permission_handler: ^11.3.1
  provider: ^6.1.2
  sprintf: ^7.0.0
  telephony: ^0.2.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/animations/
