name: thepointapp
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1
#sdk: '>=3.3.4 <4.0.0'
environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.7.0
  http: ^1.2.1
  location: ^7.0.0
  lottie: ^3.0.0
  permission_handler: ^11.3.1
  provider: ^6.1.2
  telephony: ^0.2.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/animations/
